### ISSUE TITLE
Kernel 6.8.0-51

### ISSUE THREAD

**Issue by zmisson424** [jeremyb31/bluetooth-6.8#4]
This driver is fantastic and solved all of my problems in the past. Thanks for all of the work, it is much appreciated.

My kernel was upgraded to 6.8.0-51 and this driver no longer works as intended.

When installing (with the 6.5-50 branch) 
```sudo dkms install btusb/4.1```

I get the following errors:

Building module:
Cleaning build area...
'make' all KVER=6.8.0-51-generic...(bad exit status: 2)
ERROR (dkms apport): binary package for btusb: 4.1 not found
Error! Bad return status for module build on kernel: 6.8.0-51-generic (x86_64)
Consult /var/lib/dkms/btusb/4.1/build/make.log for more information.

And the make.log outputs:
DKMS make.log for btusb-4.1 for kernel 6.8.0-51-generic (x86_64)
Thu Jan  2 08:50:35 AM CST 2025
make -C /lib/modules/6.8.0-51-generic/build M=/var/lib/dkms/btusb/4.1/bu>
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-51-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubunt>
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /var/lib/dkms/btusb/4.1/build/btusb.o
/var/lib/dkms/btusb/4.1/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: error: ‘HCI_QUIRK_VALID_L>
 4513 |                 set_bit(HCI_QUIRK_VALID_LE_STATES, &hdev->quirks>
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                         HCI_QUIRK_BROKEN_LE_STATES
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: note: each undeclared ide>
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/btusb/4.1/build/>
make[2]: *** [/usr/src/linux-headers-6.8.0-51-generic/Makefile:1925: /va>
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-51-generic'
make: *** [Makefile:7: all] Error 2

System Information:
OS: Ubuntu 24.04
Kernel: 6.8.0-51-generic

**Comment by zmisson424** [comment]
I failed to correctly install the btusb4.2 when using branch 6.8.50. This did resolve my issue and this works with Kernel 68.0-51
