### ISSUE TITLE
Make error on 6.8.0-52

### ISSUE THREAD

**Issue by zonya** [jeremyb31/bluetooth-6.8#6]
I tried to install on latest Ubuntu 24.04 LTS via command 
sudo apt install git dkms
git clone https://github.com/jeremyb31/bluetooth-6.8.git
sudo dkms add ./bluetooth-6.8
sudo dkms install btusb/4.1

On last command I got error:
Sign command: /usr/bin/kmodsign
Binary update-secureboot-policy not found, modules won't be signed

Building module:
Cleaning build area...
'make' all KVER=6.8.0-52-generic......(bad exit status: 2)
ERROR (dkms apport): binary package for btusb: 4.1 not found
Error! Bad return status for module build on kernel: 6.8.0-52-generic (x86_64)
Consult /var/lib/dkms/btusb/4.1/build/make.log for more information.

Content of make.log

DKMS make.log for btusb-4.1 for kernel 6.8.0-52-generic (x86_64)
Sat Feb  8 12:59:30 CET 2025
make -C /lib/modules/6.8.0-52-generic/build M=/var/lib/dkms/btusb/4.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-52-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /var/lib/dkms/btusb/4.1/build/btusb.o
/var/lib/dkms/btusb/4.1/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: error: ‘HCI_QUIRK_VALID_LE_STATES’ undeclared (first use in this function); did you mean ‘HCI_QUIRK_BROKEN_LE_STATES’?
 4513 |                 set_bit(HCI_QUIRK_VALID_LE_STATES, &hdev->quirks);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                         HCI_QUIRK_BROKEN_LE_STATES
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/btusb/4.1/build/btusb.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-52-generic/Makefile:1925: /var/lib/dkms/btusb/4.1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-52-generic'
make: *** [Makefile:7: all] Error 2

**Comment by jeremyb31** [comment]
Try
`cd Desktop
git clone https://github.com/jeremyb31/bluetooth-6.8.git -b 6.8.0-50
sudo dkms add ./bluetooth-6.8
sudo dkms install btusb/4.2`

**Comment by geru** [comment]
I have the same problem. Trying the suggested clone gives error `fatal: Remote branch 6.8.0-50 not found in upstream origin`

Previously, I successfully installed btusb/4.1. Installing for new kernel 6.8.0-52 gives the following make.log:

```
make -C /lib/modules/6.8.0-52-generic/build M=/var/lib/dkms/btusb/4.1/build modules
make[1]: Entering directory '/usr/src/linux-headers-6.8.0-52-generic'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /var/lib/dkms/btusb/4.1/build/btusb.o
/var/lib/dkms/btusb/4.1/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: error: ‘HCI_QUIRK_VALID_LE_STATES’ undeclared (first use in this function); did you mean ‘HCI_QUIRK_BROKEN_LE_STATES’?
 4513 |                 set_bit(HCI_QUIRK_VALID_LE_STATES, &hdev->quirks);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                         HCI_QUIRK_BROKEN_LE_STATES
/var/lib/dkms/btusb/4.1/build/btusb.c:4513:25: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:243: /var/lib/dkms/btusb/4.1/build/btusb.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.8.0-52-generic/Makefile:1925: /var/lib/dkms/btusb/4.1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.8.0-52-generic'
make: *** [Makefile:7: all] Error 2

```

btusb/4.2 doesn't seem to be an option.

**Comment by geru** [comment]
I have poor `git` skills.

When I clone with `git clone git@github.com:jeremyb31/bluetooth-6.8.git -b 6.5-50` then the option to install `btusb/4.2` becomes available and works.

Thank you very much.

**Comment by jeremyb31** [comment]
There are only a couple of places I have posted that fix for the change in the 6.8 kernel so it would have been difficult to find
