### ISSUE TITLE
Failed command: 'make' all KVER=6.10.2-rt14-arch1-5-rt

### ISSUE THREAD

**Issue by mokshraj** [jeremyb31/bluetooth-6.8#8]
only works on 6.8 i am 6.10 can you please make it work on other kernels

**Comment by jeremyb31** [comment]
What is the error message?

**Comment by mokshraj** [comment]
thanks for reply bro this is it:
           .-------------------------:                    baymax@baymax
          .+=========================.                    -------------
         :++===++==================-       :++-           OS: CachyOS x86_64
        :*++====+++++=============-        .==:           Host: Aspire Lite AL15-41
       -*+++=====+***++==========:                        Kernel: Linux 6.10.2-rt14-arch1-5-rt
      =*++++========------------:                         Uptime: 9 mins
     =*+++++=====-                     ...                Packages: 1256 (pacman), 10 (snap)
   .+*+++++=-===:                    .=+++=:              Shell: fish 4.0.1
  :++++=====-==:                     -*****+              Display (BOE0903): 1920x1080 @ 60 Hz in 15" [Built-in]
 :++========-=.                      .=+**+.              DE: GNOME 48.0
.+==========-.                          .                 WM: Mutter (Wayland)
 :+++++++====-                                .--==-.     WM Theme: Adwaita
  :++==========.                             :+++++++:    Theme: Adwaita [GTK2/3/4]
   .-===========.                            =*****+*+    Icons: Adwaita [GTK2/3/4]
    .-===========:                           .+*****+:    Font: Adwaita Sans (11pt) [GTK2/3/4]
      -=======++++:::::::::::::::::::::::::-:  .---:      Cursor: Adwaita (24px)
       :======++++====+++******************=.             Terminal: GNOME Console 48.0.1
        :=====+++==========++++++++++++++*-               Terminal Font: Adwaita Mono (11pt)
         .====++==============++++++++++*-                CPU: AMD Ryzen 5 5500U (12) @ 4.06 GHz
          .===+==================+++++++:                 GPU: AMD Lucienne [Integrated]
           .-=======================+++:                  Memory: 3.38 GiB / 14.97 GiB (23%)
             ..........................                   Swap: 0 B / 14.96 GiB (0%)
                                                          Disk (/): 198.36 GiB / 476.64 GiB (42%) - btrfs
                                                          Local IP (wlan0): 192.168.29.129/24
                                                          Battery (BAT): 100% [AC Connected]
                                                          Locale: en_IN

                                                                                  
                                                                                  
~
❯ cd Desktop
  git clone https://github.com/jeremyb31/bluetooth-6.8.git -b 6.5-50
  sudo dkms add ./bluetooth-6.8
  sudo dkms install btusb/4.2
Cloning into 'bluetooth-6.8'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (113/113), done.
remote: Total 116 (delta 42), reused 48 (delta 2), pack-reused 0 (from 0)
Receiving objects: 100% (116/116), 268.99 KiB | 134.00 KiB/s, done.
Resolving deltas: 100% (42/42), done.
[sudo] password for baymax: 

Error! DKMS tree already contains: btusb/4.2
You cannot add the same module/version combo more than once.
Sign command: /usr/lib/modules/6.10.2-rt14-arch1-5-rt/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
'make' all KVER=6.10.2-rt14-arch1-5-rt

Error! Bad return status for module build on kernel: 6.10.2-rt14-arch1-5-rt (x86_64)
Consult /var/lib/dkms/btusb/4.2/build/make.log for more information.

log :
DKMS (dkms-3.1.6) make.log for btusb/4.2 for kernel 6.10.2-rt14-arch1-5-rt (x86_64)
Sunday 30 March 2025 11:04:43 PM IST

Cleaning build area
# command: make clean
make -C /lib/modules/6.10.2-rt14-arch1-5-rt/build M=/var/lib/dkms/btusb/4.2/build clean
make[1]: Entering directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
  CLEAN   /var/lib/dkms/btusb/4.2/build/Module.symvers
make[1]: Leaving directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'

# exit code: 0
# elapsed time: 00:00:00
----------------------------------------------------------------

Building module(s)
# command: 'make' all KVER=6.10.2-rt14-arch1-5-rt
make -C /lib/modules/6.10.2-rt14-arch1-5-rt/build M=/var/lib/dkms/btusb/4.2/build modules
make[1]: Entering directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
  CC [M]  /var/lib/dkms/btusb/4.2/build/btusb.o
/var/lib/dkms/btusb/4.2/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.2/build/btusb.c:4524:25: error: ‘HCI_QUIRK_BROKEN_LE_STATES’ undeclared (first use in this function); did you mean ‘HCI_QUIRK_BROKEN_LE_CODED’?
 4524 |                 set_bit(HCI_QUIRK_BROKEN_LE_STATES, &hdev->quirks);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         HCI_QUIRK_BROKEN_LE_CODED
/var/lib/dkms/btusb/4.2/build/btusb.c:4524:25: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/btusb/4.2/build/btusb.o] Error 1
make[2]: *** [/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build/Makefile:1934: /var/lib/dkms/btusb/4.2/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
make: *** [Makefile:7: all] Error 2

# exit code: 2
# elapsed time: 00:00:02
----------------------------------------------------------------

**Comment by mokshraj** [comment]
@jeremyb31 and i have never tested or found the mention of your 6.11 version of this driver so i don't know how install it

**Comment by jeremyb31** [comment]
`git clone https://github.com/jeremyb31/bluetooth-6.11.git`
`sudo dkms add ./bluetooth-6.11`
`sudo dkms install btusb/4.1`

**Comment by mokshraj** [comment]
@jeremyb31 i tested this but gave the this make.log:
DKMS (dkms-3.1.6) make.log for btusb/4.1 for kernel 6.10.2-rt14-arch1-5-rt (x86_64)
Sunday 30 March 2025 11:35:32 PM IST

Cleaning build area
# command: make clean
make -C /lib/modules/6.10.2-rt14-arch1-5-rt/build M=/var/lib/dkms/btusb/4.1/build clean
make[1]: Entering directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
make[1]: Leaving directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'

# exit code: 0
# elapsed time: 00:00:00
----------------------------------------------------------------

Building module(s)
# command: 'make' all KVER=6.10.2-rt14-arch1-5-rt
make -C /lib/modules/6.10.2-rt14-arch1-5-rt/build M=/var/lib/dkms/btusb/4.1/build modules
make[1]: Entering directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
  CC [M]  /var/lib/dkms/btusb/4.1/build/btusb.o
/var/lib/dkms/btusb/4.1/build/btusb.c: In function ‘btusb_probe’:
/var/lib/dkms/btusb/4.1/build/btusb.c:4047:25: error: ‘HCI_QUIRK_BROKEN_LE_STATES’ undeclared (first use in this function); did you mean ‘HCI_QUIRK_BROKEN_LE_CODED’?
 4047 |                 set_bit(HCI_QUIRK_BROKEN_LE_STATES, &hdev->quirks);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         HCI_QUIRK_BROKEN_LE_CODED
/var/lib/dkms/btusb/4.1/build/btusb.c:4047:25: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/btusb/4.1/build/btusb.o] Error 1
make[2]: *** [/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build/Makefile:1934: /var/lib/dkms/btusb/4.1/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.10.2-rt14-arch1-5-rt/build'
make: *** [Makefile:6: all] Error 2

# exit code: 2
# elapsed time: 00:00:04
----------------------------------------------------------------


hence i am buildind the kernel through manger provided by the cachyos team and have disabled thier custom config

**Comment by jeremyb31** [comment]
Your kernel is too different than the Ubuntu one this is based on.  What is the USB ID of your bluetooth device?

**Comment by mokshraj** [comment]
@jeremyb31 ID 13d3:3601 IMC Networks Bluetooth Radio

**Comment by jeremyb31** [comment]
What result for `modinfo btusb|grep file`

**Comment by mokshraj** [comment]
@jeremyb31 
modinfo btusb|grep file
filename:       /lib/modules/6.10.2-rt14-arch1-5-rt/kernel/drivers/bluetooth/btusb.ko.zst

and the compilation and header updates were done but it did not work for 6.11 you gave 
i assume the makelog will be the same

**Comment by jeremyb31** [comment]
Might have to ask on arch support on how to do kernel patches, it is a simple patch for that device and only the btusb module needs to be built

**Comment by mokshraj** [comment]
@jeremyb31 really

**Comment by mokshraj** [comment]
@jeremyb31 there is a wiki for creating and applying patches:
https://wiki.archlinux.org/title/Patching_packages

**Comment by mokshraj** [comment]
@jeremyb31 i am new to the drivers and kernel patching part of linux so i don't know what i have to do to install this on my system

**Comment by jeremyb31** [comment]
Well I created these githubs based on Ubuntu kernels and I know Arch is very different

**Comment by mokshraj** [comment]
@jeremyb31 can you please port this over . i will fully co-operate for testing and anything i can since this can kust might be the only driver that works on linux for my bluetooth on laptop and many users have arch or arch based distros.

**Comment by mokshraj** [comment]
@jeremyb31 is it just btusb that needs to be replaced

**Comment by jeremyb31** [comment]
btusb just needs this under the `/* Realtek 8852BE Bluetooth devices */`
`	{ USB_DEVICE(0x13d3, 0x3601), .driver_info = BTUSB_REALTEK |
						     BTUSB_WIDEBAND_SPEECH },`
Like at https://github.com/jeremyb31/bluetooth-6.8/blob/6b5e2e35ac7762d6f465f93211f054e2d9eee178/btusb.c#L559C1-L560C36

**Comment by mokshraj** [comment]
@jeremyb31 so I can try some commads i learned from chagpt to compile the module.i learned that the it needs zst compression btusb.ro.zst and make file needs modification to build the module in arch kernel since the module location are different 
Chatgpt chat: 
https://chatgpt.com/share/67eb009f-dfbc-8005-acbb-723f338a92f1

**Comment by mokshraj** [comment]
@jeremyb31 I don't know much about kernels but could try my best to learn the patching arch. 
I did make a post on arch community support discord.
To get some help regarding it but alas, nobody replied 😭.

**Comment by jeremyb31** [comment]
It might take some time to get a reply on the forum from someone who knows something, this forum https://bbs.archlinux.org/index.php

**Comment by mokshraj** [comment]
@jeremyb31 so i need to post it here.
Thanks for the direction

**Comment by jeremyb31** [comment]
It is something likely covered in the Arch wiki somewhere

**Comment by mokshraj** [comment]
@jeremyb31 if it is,it is a damn hard thing to find

**Comment by jeremyb31** [comment]
If you post on that forum, someone is likely to post a link to the wiki

**Comment by mokshraj** [comment]
thier is a path file made by a friend on cachy os discord

**Comment by mokshraj** [comment]
![Image](https://github.com/user-attachments/assets/0edbb083-150a-4b66-b609-78e9989f29ec)
this is the changes made by him are they correct

**Comment by mokshraj** [comment]
![Image](https://github.com/user-attachments/assets/538fe915-c1a1-4c7f-9b19-c5946b5e7665)
this is how i fixed it in arch

**Comment by mokshraj** [comment]
https://drive.google.com/file/d/1Z9vkXvVz_rRfHRY2qCYVcfeYdk2Gemp7/view?usp=sharing 
this is the patch file is used given by him

**Comment by mokshraj** [comment]
please credit happy not me

**Comment by mokshraj** [comment]
@jeremyb31 hope this helps you make this driver accesible to arch users

**Comment by mokshraj** [comment]
@jeremyb31 and this is the attached image in the chat 

![Image](https://github.com/user-attachments/assets/54c0bffb-fe6a-49c1-b732-e5317f7a8f59)

**Comment by mokshraj** [comment]
> > `git clone https://github.com/jeremyb31/bluetooth-6.11.git` `sudo dkms add ./bluetooth-6.11` `sudo dkms install btusb/4.1`
> 
> for this command to work in debian 13 kernel 6.12.41 
> I changed the files 
> ATH3K.c
> BTRTL.c
> BTUSB.c.
> 
> Change this line:
> include asm/unaligned.h
> include linux/unaligned.h

Thanks, actually It initially didn't work because of the difference between debian and arch kernel.
